language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.5
    - os: linux
      python: 3.4
    - os: linux
      python: 2.7

install:
  - pip install nox-automation

script:
  # penaltymodel.core
  - |
      if [[ -n $(grep core target_packages) ]]; then
        nox -f core/nox.py
      fi
