language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: "2.7"
          env: TOXENV=py27
          deploy:
        - os: linux
          sudo: required
          python: "3.6"
          env: TOXENV=py36
        - os: linux
          sudo: required
          python: "3.5"
          env: TOXENV=py36
          deploy:
        - os: linux
          sudo: required
          python: "nightly"
          env: TOXENV=pynightly
          deploy:
        - os: osx
          language: generic
          env: TOXENV=py27
          before_install:
            - brew update
            - virtualenv env -p python2
            - source env/bin/activate
          deploy:
        - os: osx
          language: generic
          env: TOXENV=py36
          before_install:
            - brew update
            - brew upgrade python
            - pip install virtualenv
            - virtualenv env -p python
            - source env/bin/activate
          deploy:

install:
    - pip install -r requirements.txt
    - pip install .
    - pip install coveralls
    
script:
- coverage run -m unittest discover

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "dwtools"
  password:
    secure: "EXy2rANHPhK+yL/0SE66R+06TZu71y/5UylpDl5BiU80T65dtkUpsfUJ2ViFNF28xhrFoT3w8dGu7AzZIyVBHLtKQxfPnXOcvkAt0Bw7Zr8F2E37XKZHMy6jbAJILL71fZ5sbexjh4qIp3nAGNePVpQStaztrCPNLHrAuO08zepeKpaKcqsCLHiFaFPvSbSGN3RnajEN5fdfy6HRng3GXNa41vohLRH8S8XzbNVHQSSYY0T7N6vRkSHa3oMwxmoHmVXbVH/KHhPN6WvKVCmF36183U+6GzbuG8J6VioX+RK6t0/ilW29wZzAviKRlWiCmbW4jgspo8odMeZMbyxp4TYESTLOzudkYi7pFCBp4jGpsK5C4lfMs33+xKVImcmHyygO6gRWDLyMPk7YbJIUcWSR9f5f7QSUFImwCpL4inWIEXckv8nNI1vhwhM0Pmrrj3JAvS9rSZdc9HqzlMtvo6zxlW/D4txa3BF56wrEal6jy5Zp4v6bM2BLozgJ6ZWlG6SUQjqZnNA3V/Xv6a0aAiiyIDkdLv9AKJl3w/tJQD1sVxZYmAYxZJ9eciQsa10of8nLjYLONryN8tteXN1cdMd5aqmicyvAcKbkwVTi9JdEGgtIovfHPqvdAhCduY2egvWTJRk4DhXO0A7/qZ5dyoF8b0eD9EXvF4rJaRmp1gI="
  distributions: "sdist bdist_wheel"
  on:
    tags: true